"use client";
import Link from "next/link";
import { useState } from "react";
import { createPortal } from "react-dom";
import { BookOpen, ClipboardList, FilePlus2, FileText, Loader2, PlayCircle, Plus, Trash2, Video, X } from "lucide-react";
import type { useCourseEditor } from "../hooks/use-course-editor";

const input = "mt-2 w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm outline-none focus:border-bkhn-red focus:bg-white";
export default function QuickLessonModal({ w }: { w: ReturnType<typeof useCourseEditor> }) {
  const [additionalDocuments, setAdditionalDocuments] = useState<number[]>([]);
  const close = () => w.setLessonModal({ open: false, chapterId: null, editing: null });
  const sections = [
    { title: "1. Lý thuyết", note: "Video YouTube", icon: PlayCircle, value: w.lessonVideoTheoryUrl, set: w.setLessonVideoTheoryUrl, placeholder: "https://youtube.com/watch?v=…" },
    { title: "2. Thực hành", note: "Video hướng dẫn", icon: Video, value: w.lessonVideoPracticeUrl, set: w.setLessonVideoPracticeUrl, placeholder: "https://youtube.com/watch?v=…" },
    { title: "3. Tài liệu", note: "PDF / Google Drive", icon: FileText, value: w.lessonDocUrl, set: w.setLessonDocUrl, placeholder: "https://drive.google.com/file/d/…" },
  ];
  return createPortal(<div className="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto bg-black/45 p-3 backdrop-blur-sm sm:p-5"><section role="dialog" aria-modal="true" aria-labelledby="quick-lesson-title" className="my-3 flex min-h-[min(760px,calc(100vh-24px))] w-full max-w-6xl flex-col overflow-hidden rounded-3xl border border-bkhn-pink bg-[#faf9fa] shadow-2xl animate-fade-in sm:my-5">
    <header className="flex items-start justify-between gap-4 border-b border-bkhn-pink bg-white px-5 py-4 sm:px-7"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-bkhn-red">Bản soạn nhanh</p><h2 id="quick-lesson-title" className="mt-1 text-xl font-black text-gray-900 sm:text-2xl">{w.lessonModal.editing ? "Chỉnh nhanh bài học" : "Tạo bài học mới"}</h2><p className="mt-1 text-xs text-gray-500">Thiết lập khung nội dung trong một màn hình; câu hỏi và tài liệu nâng cao bổ sung ở trình soạn chi tiết.</p></div><button type="button" disabled={w.isSubmitting} onClick={close} aria-label="Đóng" className="rounded-xl p-2 text-gray-500 hover:bg-gray-100"><X size={20} /></button></header>
    <form onSubmit={w.handleLessonSubmit} className="flex min-h-0 flex-1 flex-col"><div className="grid flex-1 gap-5 overflow-y-auto p-4 sm:p-6 lg:grid-cols-[minmax(260px,0.7fr)_minmax(0,1.7fr)]">
      <aside className="space-y-4 lg:sticky lg:top-0 lg:self-start"><div className="rounded-2xl border border-bkhn-pink bg-white p-5"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-bkhn-rose text-bkhn-red"><BookOpen size={22} /></span><label className="mt-4 block text-xs font-bold text-gray-600">Tên bài học <span className="text-red-600">*</span><input autoFocus name="title" required maxLength={250} value={w.formTitle} onChange={e => w.setFormTitle(e.target.value)} placeholder="Ví dụ: Các dạng bài suy luận" className={`${input} text-base font-bold`} /></label><div className="mt-5"><p className="text-xs font-bold text-gray-600">Trạng thái</p><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={() => w.setLessonStatus("DRAFT")} aria-pressed={w.lessonStatus === "DRAFT"} className={`rounded-xl border px-3 py-3 text-xs font-bold ${w.lessonStatus === "DRAFT" ? "border-gray-800 bg-gray-800 text-white" : "border-gray-200 bg-gray-50 text-gray-500"}`}>Bản nháp</button><button type="button" onClick={() => w.setLessonStatus("PUBLISHED")} aria-pressed={w.lessonStatus === "PUBLISHED"} className={`rounded-xl border px-3 py-3 text-xs font-bold ${w.lessonStatus === "PUBLISHED" ? "border-green-600 bg-green-600 text-white" : "border-gray-200 bg-gray-50 text-gray-500"}`}>Xuất bản</button></div></div></div>
        <div className="rounded-2xl border border-amber-100 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><b>Lưu ý:</b> xuất bản ngay có thể làm bài xuất hiện với học sinh nếu cụm và khóa học cũng đã mở. Chỉ thêm các phần phù hợp; không cần đủ bốn phần.</div>
      </aside>
      <div className="grid content-start gap-3 sm:grid-cols-2">{sections.map(({ title, note, icon: Icon, value, set, placeholder }) => <article key={title} className="rounded-2xl border border-gray-200 bg-white p-4 shadow-bkhn-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-bkhn-rose p-2 text-bkhn-red"><Icon size={18} /></span><div><h3 className="text-sm font-black text-gray-800">{title}</h3><p className="text-[10px] text-gray-400">{note}</p></div></div><label className="mt-4 block text-[11px] font-bold text-gray-500">Link nội dung<input type="url" value={value} onChange={e => set(e.target.value)} placeholder={placeholder} className={input} /></label><p className="mt-2 text-[10px] leading-4 text-gray-400">Tùy chọn · Để trống nếu bài không có phần này.</p>{title === "3. Tài liệu" && <div className="mt-4 border-t border-gray-100 pt-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-xl bg-bkhn-rose p-2 text-bkhn-red"><FilePlus2 size={18} /></span><div><h3 className="text-sm font-black text-gray-800">Tài liệu bổ sung</h3><p className="text-[10px] text-gray-400">Tùy chọn · Lưu cùng bài học</p></div></div><button type="button" disabled={additionalDocuments.length >= 10} onClick={() => setAdditionalDocuments(items => [...items, (items.at(-1) ?? 0) + 1])} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-bkhn-pink bg-bkhn-rose px-3 text-xs font-bold text-bkhn-red disabled:opacity-40"><Plus size={15} />Thêm link tài liệu</button></div>
          {additionalDocuments.length === 0 ? <p className="mt-4 rounded-xl border border-dashed border-gray-200 p-4 text-center text-xs text-gray-400">Có thể thêm nhiều tài liệu cho phần này.</p> : <div className="mt-4 space-y-3">{additionalDocuments.map((key, index) => <div key={key} className="grid gap-2 rounded-xl bg-gray-50 p-3 sm:grid-cols-[0.7fr_1.3fr_auto]"><input name="additionalDocumentTitle" required maxLength={250} defaultValue={`Tài liệu ${index + 2}`} aria-label={`Tên tài liệu ${index + 2}`} className={input.replace("mt-2 ", "")} /><input name="additionalDocumentUrl" required type="url" placeholder="Link tệp Google Drive" aria-label={`Link tài liệu ${index + 2}`} className={input.replace("mt-2 ", "")} /><button type="button" onClick={() => setAdditionalDocuments(items => items.filter(item => item !== key))} aria-label={`Xóa tài liệu ${index + 2}`} className="rounded-xl p-2 text-gray-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={16} /></button></div>)}</div>}
          <p className="mt-3 text-[10px] leading-4 text-gray-400">Các link bổ sung được lưu khi bấm tạo hoặc lưu bài học.</p>
        </div>}</article>)}
        <article className="rounded-2xl border border-gray-200 bg-white p-4 shadow-bkhn-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-white p-2 text-bkhn-red"><ClipboardList size={18} /></span><div><h3 className="text-sm font-black text-gray-800">4. Bài tập</h3><p className="text-[10px] text-gray-400">Tùy chọn · Câu hỏi & PDF gốc</p></div></div><label className="mt-4 block text-[11px] font-bold text-gray-500">PDF bài tập<input type="url" value={w.lessonExerciseUrl} onChange={e => w.setLessonExerciseUrl(e.target.value)} placeholder="Link Google Drive (tùy chọn)" className={input} /></label><label className="mt-3 block text-[11px] font-bold text-gray-500">PDF đáp án<input type="url" value={w.lessonAnswerUrl} onChange={e => w.setLessonAnswerUrl(e.target.value)} placeholder="Link Google Drive (tùy chọn)" className={input} /></label><p className="mt-3 text-[10px] leading-4 text-gray-500">Tạo câu hỏi, đáp án, lời giải và quy tắc chấm trong trình soạn chi tiết sau khi lưu bài.</p></article>

      </div>
    </div><footer className="flex flex-wrap items-center justify-between gap-3 border-t border-bkhn-pink bg-white px-5 py-4 sm:px-7"><div className="text-[11px] text-gray-500">Các link hợp lệ phải dùng HTTP/HTTPS. Có thể lưu bài chỉ với tên.</div><div className="flex flex-wrap gap-2"><button type="button" disabled={w.isSubmitting} onClick={close} className="min-h-11 rounded-xl px-4 text-sm font-bold text-gray-600 hover:bg-gray-100">Hủy</button>{w.lessonModal.editing && <Link href={`/dashboard/lessons/${w.lessonModal.editing.id}/questions`} className="inline-flex min-h-11 items-center rounded-xl border border-bkhn-pink px-4 text-sm font-bold text-bkhn-red">Mở trình soạn chi tiết</Link>}<button name="intent" value="stay" disabled={w.isSubmitting} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-bkhn-red px-5 text-sm font-bold text-white shadow-bkhn-md disabled:opacity-50">{w.isSubmitting && <Loader2 size={16} className="animate-spin" />}{w.lessonModal.editing ? "Lưu thay đổi" : "Tạo bài học"}</button>{!w.lessonModal.editing && <button name="intent" value="open" disabled={w.isSubmitting} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-gray-900 px-5 text-sm font-bold text-white disabled:opacity-50">Tạo & soạn chi tiết →</button>}</div></footer></form>
  </section></div>, document.body);
}
