"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { AtSign, CheckCircle2, Loader2, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import type { SessionUser } from "@/features/auth/types";
import { adminJson, errorMessage } from "@/features/admin/api";
import RequestError from "@/features/admin/components/request-error";
import PasswordForm from "./password-form";

const input = "mt-2 w-full rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm outline-none focus:border-bkhn-red focus:bg-white";
export default function AdminAccountSettings({ user }: { user: SessionUser }) {
  const router = useRouter();
  const [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [message, setMessage] = useState<string | null>(null);
  const initials = (user.name || user.email).split(/\s+/).slice(0, 2).map(part => part[0]).join("").toUpperCase();
  return <div className="mx-auto max-w-6xl space-y-5 animate-fade-up">
    <header className="overflow-hidden rounded-3xl border border-bkhn-pink bg-gradient-to-br from-white via-white to-bkhn-rose shadow-bkhn-sm"><div className="grid gap-6 p-6 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-center"><div className="flex items-start gap-4"><span className="rounded-2xl bg-white p-3 text-bkhn-red ring-1 ring-bkhn-pink"><ShieldCheck size={24} /></span><div><p className="text-[11px] font-black uppercase tracking-[0.18em] text-bkhn-red">Bảo mật & danh tính</p><h1 className="mt-2 text-2xl font-black tracking-tight text-gray-900 sm:text-3xl">Tài khoản quản trị</h1><p className="mt-2 max-w-xl text-sm leading-6 text-gray-500">Cập nhật thông tin hiển thị và bảo vệ tài khoản đang điều hành toàn bộ nội dung học tập.</p></div></div><div className="flex min-w-0 items-center gap-3 rounded-2xl border border-bkhn-pink bg-white/90 p-4 shadow-sm"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-bkhn-red text-sm font-black text-white">{initials}</span><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate text-sm font-black text-gray-900">{user.name || "Quản trị viên"}</p><span className="rounded-full bg-green-50 px-2 py-0.5 text-[9px] font-black uppercase text-green-700">Đang hoạt động</span></div><p className="mt-1 truncate text-xs text-gray-500">{user.email}</p><p className="mt-1 flex items-center gap-1 text-[10px] font-bold text-bkhn-red"><Sparkles size={11} />Quyền quản trị hệ thống</p></div></div></div></header>
    <div className="grid items-start gap-5 lg:grid-cols-2">
      <section className="rounded-3xl border border-gray-200 bg-white p-6 shadow-bkhn-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-bkhn-rose text-sm font-black text-bkhn-red">01</span><div><h2 className="font-black text-gray-900">Thông tin tài khoản</h2><p className="mt-1 text-xs text-gray-500">Tên và email dùng trong khu vực quản trị.</p></div></div>
        <form className="mt-6 space-y-4" onSubmit={async event => { event.preventDefault(); if (busy) return; const values = Object.fromEntries(new FormData(event.currentTarget)); setBusy(true); setError(null); setMessage(null); try { await adminJson("/api/admin/account/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); setMessage("Đã cập nhật thông tin tài khoản."); router.refresh(); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }}><label className="block text-xs font-bold text-gray-600">Tên hiển thị<div className="relative"><UserRound size={16} className="absolute left-4 top-5 text-gray-400" /><input name="name" required maxLength={100} defaultValue={user.name ?? ""} className={`${input} pl-11`} /></div></label><label className="block text-xs font-bold text-gray-600">Email đăng nhập<div className="relative"><AtSign size={16} className="absolute left-4 top-5 text-gray-400" /><input name="email" type="email" required maxLength={254} defaultValue={user.email} className={`${input} pl-11`} /></div></label><RequestError message={error} />{message && <p role="status" className="flex items-center gap-2 rounded-xl bg-green-50 p-3 text-xs font-medium text-green-800"><CheckCircle2 size={15} />{message}</p>}<button disabled={busy} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-bkhn-red px-5 text-sm font-bold text-white disabled:opacity-50">{busy && <Loader2 size={16} className="animate-spin" />}Lưu thông tin</button></form>
      </section>
      <section className="rounded-3xl border border-gray-200 bg-white p-6 shadow-bkhn-sm"><div className="mb-6 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-50 text-sm font-black text-amber-700">02</span><div><h2 className="font-black text-gray-900">Mật khẩu & phiên đăng nhập</h2><p className="mt-1 text-xs text-gray-500">Thay đổi nhạy cảm cần xác nhận mật khẩu hiện tại.</p></div></div><PasswordForm compact /></section>
    </div>
    <aside className="rounded-2xl border border-blue-100 bg-blue-50/60 p-4 text-xs leading-6 text-blue-900"><b>Gợi ý bảo mật:</b> dùng mật khẩu riêng cho hệ thống này. Sau khi đổi mật khẩu, mọi phiên quản trị — kể cả phiên hiện tại — đều bị đăng xuất.</aside>
  </div>;
}
