import { test } from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { prisma } from "../../server/db/prisma";
import { createLesson, createQuestion, updateQuestion, updateLesson } from "../../server/admin/content-mutations";
import { performLearningAction as act, getLearningLesson } from "../../server/learning/service";
import { attachmentDownload } from "../../server/learning/attachment-access";
import { finishContentSteps } from "../helpers/learning-workflow";
import type { SessionUser } from "../../features/auth/types";
import type { Answers, QuizSnapshot } from "../../features/learning/quiz-session";

test("Phase 4: resume, permissions, frozen snapshots, deadline, exactly-once grading and isolated preview", { timeout: 360000 }, async () => {
  assert.equal(process.env.ALLOW_INTEGRATION_TESTS, "1", "Only the approved test database.");
  const actor = (role: "STUDENT" | "ADMIN"): SessionUser => ({ id: randomUUID(), email: `${randomUUID()}@example.invalid`, name: "Phase 4 fixture", role });
  const student = actor("STUDENT"), other = actor("STUDENT"), admin = actor("ADMIN");
  let courseId: string | undefined;
  try {
    await prisma.user.createMany({ data: [student, other, admin].map(user => ({ ...user, passwordHash: "test-only" })) });
    const course = await prisma.course.create({ data: { title: "Phase 4 fixture", status: "PUBLISHED" } }); courseId = course.id;
    const stage = await prisma.stage.create({ data: { title: "Stage", courseId, order: 0 } });
    const subject = await prisma.subject.create({ data: { title: "Subject", stageId: stage.id, order: 0 } });
    const chapter = await prisma.chapter.create({ data: { title: "Chapter", subjectId: subject.id, order: 0, status: "PUBLISHED" } });
    const lesson = await createLesson({ chapterId: chapter.id, title: "Sequential quiz", videoTheoryUrl: "https://youtube.com/watch?v=dQw4w9WgXc", videoPracticeUrl: "https://youtube.com/watch?v=dQw4w9WgXc", status: "PUBLISHED", stepNavigation: "SEQUENTIAL", requireCompletionForNext: true, completionMode: "QUIZ_PASSED", quizTimeLimitMinutes: 45, quizMaxAttempts: 2, quizPassPercent: 60, quizShuffleQuestions: true, quizShuffleAnswers: true, documentUrl: "https://example.com/notes.pdf" });
    const next = await createLesson({ chapterId: chapter.id, title: "Next", status: "PUBLISHED", documentUrl: "https://example.com/next-notes.pdf" });
    const question = await createQuestion({ lessonId: lesson.id, type: "MULTIPLE_CHOICE", content: "Original", options: ["A", "B", "C", "D"].map(id => ({ id, text: id })), correctAnswer: "B", explanation: "Original secret" });
    const short = await createQuestion({ lessonId: lesson.id, type: "SHORT_ANSWER", content: "Short", correctAnswer: "2" });
    assert.equal((await getLearningLesson(student, next.id)).locked, true);
    assert.equal((await getLearningLesson(student, lesson.id)).documentUrl, null);
    const file = await prisma.lessonAttachment.findFirstOrThrow({ where: { lessonId: lesson.id } });
    await assert.rejects(attachmentDownload(student, file.id), /chưa mở/);
    await assert.rejects(act(student, lesson.id, { action: "STEP", step: 2, complete: true }), /phần trước/);
    await assert.rejects(act(student, lesson.id, { action: "START", requestId: randomUUID() }), /Chưa mở/);
    await assert.rejects(act(student, lesson.id, { action: "COMPLETE" }), /các phần có nội dung/);
    await finishContentSteps(student, lesson.id);
    assert.equal((await getLearningLesson(student, lesson.id)).workflow?.currentStep, 3);
    const requestId = randomUUID();
    const started = await act(student, lesson.id, { action: "START", requestId });
    const session = started.view.workflow!.session!;
    const retry = await act(student, lesson.id, { action: "START", requestId });
    assert.equal(retry.view.workflow!.session!.id, session.id);
    assert.equal(retry.view.workflow!.session!.deadlineAt, session.deadlineAt);
    assert.deepEqual(retry.view.questions, started.view.questions);
    assert.equal(await prisma.quizSession.count({ where: { userId: student.id } }), 1);
    assert.ok(!JSON.stringify(started.view).includes("Original secret"));
    assert.ok(!JSON.stringify(started.view).includes("correctAnswer"));
    await updateQuestion(question.id, { content: "Edited", correctAnswer: "A", explanation: "Edited secret" });
    await prisma.question.delete({ where: { id: short.id } });
    await updateLesson(lesson.id, { quizTimeLimitMinutes: 1, quizPassPercent: 100 });
    const stored = await prisma.quizSession.findUniqueOrThrow({ where: { id: session.id } });
    assert.equal((stored.snapshot as unknown as QuizSnapshot).passPercent, 60);
    assert.equal((stored.snapshot as unknown as QuizSnapshot).questions.length, 2);
    const answers: Answers = { [question.id]: "B", [short.id]: "2" };
    await assert.rejects(act(other, lesson.id, { action: "SAVE", sessionId: session.id, revision: 0, answers }), /Chưa mở|không thuộc/);
    await assert.rejects(act(student, lesson.id, { action: "SYNC", preview: true }), /quản trị viên/);
    const saved = await act(student, lesson.id, { action: "SAVE", sessionId: session.id, revision: 0, answers });
    const reloaded = await getLearningLesson(student, lesson.id);
    assert.deepEqual(reloaded.workflow!.session!.answers, answers);
    assert.equal(reloaded.workflow!.session!.deadlineAt, session.deadlineAt);
    await assert.rejects(act(student, lesson.id, { action: "SAVE", sessionId: session.id, revision: 0, answers: {} }), /tab khác/);
    const revision = saved.view.workflow!.session!.revision;
    const [first, duplicate] = await Promise.all([1, 2].map(() => act(student, lesson.id, { action: "SUBMIT", sessionId: session.id, revision, answers })));
    assert.equal(first.score, 100); assert.equal(duplicate.score, 100);
    assert.equal(first.feedback?.find(item => item.questionId === question.id)?.explanation, "Original secret");
    assert.equal(await prisma.exerciseAttempt.count({ where: { sessionId: session.id } }), 1);
    assert.equal(await prisma.learningActivity.count({ where: { userId: student.id, type: "EXERCISE_SUBMITTED" } }), 1);
    assert.equal(first.view.completed, true);
    assert.equal((await getLearningLesson(student, next.id)).locked, false);

    const second = (await act(student, lesson.id, { action: "START", requestId: randomUUID() })).view.workflow!.session!;
    await act(student, lesson.id, { action: "SAVE", sessionId: second.id, revision: 0, answers: { [question.id]: "B" } });
    await prisma.quizSession.update({ where: { id: second.id }, data: { deadlineAt: new Date(Date.now() - 1000) } });
    const expired = await act(student, lesson.id, { action: "SUBMIT", sessionId: second.id, revision: 1, answers: { [question.id]: "A" } });
    assert.equal(expired.score, 0); assert.equal(expired.timedOut, true);
    assert.deepEqual(expired.view.workflow!.session!.answers, { [question.id]: "B" });
    await act(student, lesson.id, { action: "SUBMIT", sessionId: second.id, revision: 1, answers: {} });
    assert.equal(await prisma.exerciseAttempt.count({ where: { userId: student.id } }), 2);
    await assert.rejects(act(student, lesson.id, { action: "START", requestId: randomUUID() }), /hết số lần/);

    await finishContentSteps(admin, lesson.id, { preview: true });
    const simulated = (await act(admin, lesson.id, { action: "START", requestId: randomUUID(), preview: true })).view.workflow!.session!;
    const previewResult = await act(admin, lesson.id, { action: "SUBMIT", sessionId: simulated.id, revision: 0, answers: { [question.id]: "A" }, preview: true });
    assert.equal(previewResult.score, 100); assert.equal(previewResult.view.completed, true);
    assert.equal((await getLearningLesson(admin, lesson.id, { preview: true })).workflow?.session?.id, simulated.id);
    for (const count of [await prisma.progress.count({ where: { userId: admin.id } }), await prisma.exerciseAttempt.count({ where: { userId: admin.id } }), await prisma.learningActivity.count({ where: { userId: admin.id } })]) assert.equal(count, 0);
    await act(admin, lesson.id, { action: "RESET_PREVIEW", preview: true });
    assert.equal(await prisma.quizSession.count({ where: { userId: admin.id } }), 0);
    assert.equal(await prisma.exerciseAttempt.count({ where: { userId: student.id } }), 2);
    await assert.rejects(act(student, lesson.id, { action: "RESET_PREVIEW" }), /Preview/);
    await finishContentSteps(student, next.id);
    assert.equal((await act(student, next.id, { action: "COMPLETE" })).view.completed, true);
  } finally {
    if (courseId) await prisma.course.deleteMany({ where: { id: courseId } });
    await prisma.user.deleteMany({ where: { id: { in: [student.id, other.id, admin.id] } } });
    await prisma.$disconnect();
  }
});
